# This is a basic workflow to help you get started with Actions

name: Deploy docs on heroku

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Setup python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx
      
      - name: "Build docs (sphinx)"
        run: |
          cd ./docs/apiref
          sh build.sh
      
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.8.8 
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          appdir: docs
